version: "3"

volumes:
  data: {}

services:
  api:
    image: kjhabc2002/deer-assignment
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn deer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/usr/src/app/staticifiles
    ports:
      - 8000:8000
    restart: always
    env_file: 
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  
    